# Generated by Django 4.2.3 on 2023-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='product',
        ),
        migrations.AddField(
            model_name='highlights',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
