# Generated by Django 4.2.3 on 2024-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='enable_sample',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
