# Generated by Django 4.2.3 on 2024-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_enable_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_query',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
